### ISSUE TITLE
Overriding got table

### ISSUE THREAD

**Issue by nitanmarcel** [reveny/Android-GUI-Injector#10]
Could the app also be edited to override GOT tables so we can intercept function calls? Obviously speaking about the ptrace injection , since LD_PRELOAD automatically do that .

I've tried doing myself but all of this overcomes me so I gave up after a few attempts.

**Comment by reveny** [comment]
Well if you are talking about patching memory such as overwriting a function with a nop instruction to make it not execute then yes, you can use ptrace_write for that. I don't recommend doing it with ptrace though. There is a system call called process_vm_writev you should look into that for what you want to do.

**Comment by nitanmarcel** [comment]
> Well if you are talking about patching memory such as overwriting a function with a nop instruction to make it not execute then yes, you can use ptrace_write for that. I don't recommend doing it with ptrace though. There is a system call called process_vm_writev you should look into that for what you want to do.

Found a way of doing what I need with funchook, so I can intercepting function calls and editing their value which works perfectly fine. Thanks for suggestion anyway :)

Only issue I have is that I need to manually open the so file and dlsym to load it into the program but that works fine.


Leaving here the code for this if anyone is interested

https://bin.kv2.dev/~6448e657e599576ea02c45b9

**Comment by nitanmarcel** [comment]
Another solution that I've found very useful, and which will support all the arches supported by this is [bytehook](https://github.com/bytedance/bhook) . Only issue is that not being inline, it can only inject only at the start of a function. Another library is [ShadowHook](https://github.com/bytedance/android-inline-hook) but only supports armeabi-v7a and arm64-v8a. But they both can now be used starting with the last commits since the hooks need to be done after the library has been constructed (in a separate function for example)
