### ISSUE TITLE
BlueStack x86 crash after inject

### ISSUE THREAD

**Issue by quangtungvl** [reveny/Android-GUI-Injector#13]
App/Game crash ...black screen after inject successful
![bluestack_crash_2](https://github.com/reveny/Android-DLL-Injector/assets/17865762/03e49001-e67c-457a-974c-1fa606b25ee8)
![bluestack_crash_1](https://github.com/reveny/Android-DLL-Injector/assets/17865762/163d5ee6-ae30-4f0d-95fd-00a5664b0541)

![bluestack_crash](https://github.com/reveny/Android-DLL-Injector/assets/17865762/528f0e9c-359c-4f26-be10-5e09e5a4f1c8)

**Comment by reveny** [comment]
It looks like the Injection was successful but I am not sure if google chrome has some kind of protection against Injection, could you try it on a different app/game.

**Comment by reveny** [comment]
Update: It's a problem with disabling SELinux. Instead of setting SELinux from code, it should be done manually through ADB

**Comment by reveny** [comment]
Fixed in V2
