### ISSUE TITLE
Writing to process failed Result: -1

### ISSUE THREAD

**Issue by catchmeifyouc4n** [reveny/Android-GUI-Injector#14]
![Screenshot_2023-10-16-00-12-42-556_com vphonegaga titan](https://github.com/reveny/Android-GUI-Injector/assets/148013104/a35d920b-e469-4179-a219-056e3eb2d841)
![Screenshot_2023-10-16-00-12-33-382_com vphonegaga titan](https://github.com/reveny/Android-GUI-Injector/assets/148013104/019ffac4-86a9-49db-b899-10388d4ac458)
![Screenshot_2023-10-16-00-12-22-277_com vphonegaga titan](https://github.com/reveny/Android-GUI-Injector/assets/148013104/4d10bd13-927f-4593-b199-5eacea3c66dd)

**Comment by catchmeifyouc4n** [comment]
![Screenshot_2023-10-16-00-22-23-442_com reveny injector](https://github.com/reveny/Android-GUI-Injector/assets/148013104/20c34868-a0ee-4ca6-8702-431130384495)

**Comment by catchmeifyouc4n** [comment]
![Screenshot_2023-10-16-00-22-23-442_com reveny injector](https://github.com/reveny/Android-GUI-Injector/assets/148013104/82461e81-d329-42db-b6a7-773482f5b968)



Why dont work((

**Comment by catchmeifyouc4n** [comment]
Its bad virtual space. Softwark work so good.

**Comment by reveny** [comment]
Please check V2 if the issue is fixed
