### ISSUE TITLE
Dlopen failed for Bluestacks X86_64 Android 9 (Pie) rooted using Magisk Delta/Supersu

### ISSUE THREAD

**Issue by cfhook** [reveny/Android-GUI-Injector#15]
![image](https://github.com/reveny/Android-GUI-Injector/assets/150492660/448c8c03-d1ed-4f17-ba27-8883f19b49ac)

**Comment by cfhook** [comment]
I also tried normal supersu root, not work with Bluestacks 5, but I tested on Bluestacks 5 x86 Android 7 it work.

**Comment by cfhook** [comment]
I tested android 11 x86_64 Bluestacks 5, it work

**Comment by cfhook** [comment]
> What's that app for logs?

Android studio log cat

**Comment by 0NullBit0** [comment]
My Injector works for bluestack android pie too https://github.com/0NullBit0/NullTrace-Android-Inject the reason for handle 0x0 is linker namespace restrictions
