### ISSUE TITLE
Does not work on non-rooted devices

### ISSUE THREAD

**Issue by yjimenez15** [reveny/Android-GUI-Injector#16]
My cell phone is a Xiaomi Redmi Note 10 with Android 12 and it is not rooted. Every time I try to inject a shared library it doesn't do anything and it doesn't show any information in the Logs either.

![image](https://github.com/reveny/Android-GUI-Injector/assets/64601802/5b0e7975-9d9f-48db-90c1-912672e6a10a)

![image](https://github.com/reveny/Android-GUI-Injector/assets/64601802/52609450-db23-4316-9a03-61829a4937a9)

Please, How I can fix that ?

**Comment by reveny** [comment]
Not possible to Inject without root.
