### ISSUE TITLE
Little stupid question.

### ISSUE THREAD

**Issue by whoamiCMD** [reveny/Android-GUI-Injector#18]
**Hello.
For what its project?
Me injected native library(.so) with ImGui in game.
ImGui does not appear. Its my bad?**

Sorry for question.

**Comment by reveny** [comment]
To verify if the injection was correct, you can:
1. Check the injection logs in the log tab
2. Check the logcat for possible logs of the library you injected
3. Run "cat /proc/$(pidof com.package.name)/maps | grep libyourlibraryname.so" in termux or adb as root.
