### ISSUE TITLE
Not working on MuMu Emulator 12

### ISSUE THREAD

**Issue by binaryslark** [reveny/Android-GUI-Injector#20]
logcat output : [crash.txt](https://github.com/user-attachments/files/15584145/crash.txt)

**Comment by reveny** [comment]
The crash seems to be happening here
https://github.com/reveny/Android-GUI-Injector/blob/e0fe06e3a443422421314d096a497b93396f432a/app/src/main/jni/Injector/Injector.cpp#L149

I am unsure why this would crash in the first place but I assume it's some issue of the emulator itself as there isn't any clear reason why this wouldn't work.
My guess is that libsu causes this problem and the native app isn't able to find the native class in the dex. I will look into this and maybe create an issue for libsu.
