### ISSUE TITLE
ARM PLATFORM ERROR

### ISSUE THREAD

**Issue by JoelitonMods** [reveny/Android-GUI-Injector#3]
On x86 it is injecting successfully, but on armeabi-v7a it is not injecting.

**Comment by reveny** [comment]
Could you please provide the logcat so I can investigate the problem.

**Comment by JoelitonMods** [comment]
![image](https://user-images.githubusercontent.com/90171592/195010623-1952df47-1def-403b-9a8e-c7768ca28412.png)

**Comment by JoelitonMods** [comment]
![image](https://user-images.githubusercontent.com/90171592/195010693-a73b2ebe-7235-4d0e-b9fb-7ba6cb1b38af.png)

armeabi-v7a

**Comment by JoelitonMods** [comment]
![Screenshot_2022 10 11_03 12 49 394](https://user-images.githubusercontent.com/90171592/195010775-43db04c0-2df3-49ee-a2ed-31c86a86680e.png)

x86

**Comment by reveny** [comment]
Found the problem #2

**Comment by JoelitonMods** [comment]
yes I know that, but when you inject the x86 lib in armeabi-v7a you can't use the hook, for example, MSHOOK when you use the game it closes immediately or freezes and it's not just the MSHOOK that happens I tested several hooks and both give the same error

**Comment by reveny** [comment]
I don't think I am able to fix this issue. You could try using a x86 Hooking framework. If that does not work, then the only way to make this work is by using a real device instead of an emulator. If you have Telegram I can add you there and help you with any further questions.

**Comment by JoelitonMods** [comment]
ok bro my telegram : @JOELLITONMODS

**Comment by reveny** [comment]
can you add me please: https://t.me/Reveny1

**Comment by 77friends** [comment]
> yes I know that, but when you inject the x86 lib in armeabi-v7a you can't use the hook, for example, MSHOOK when you use the game it closes immediately or freezes and it's not just the MSHOOK that happens I tested several hooks and both give the same error

Imgui works fine with dobbyhook on x86 on emulator, I tried it on forward assault (game does not have x86, only armv7 and 64) and it renders just fine.

There should be no issue with hooking.

**Comment by JoelitonMods** [comment]
thank you i will try it

**Comment by WhiskyModz** [comment]
> > yes I know that, but when you inject the x86 lib in armeabi-v7a you can't use the hook, for example, MSHOOK when you use the game it closes immediately or freezes and it's not just the MSHOOK that happens I tested several hooks and both give the same error
> 
> Imgui works fine with dobbyhook on x86 on emulator, I tried it on forward assault (game does not have x86, only armv7 and 64) and it renders just fine.
> 
> There should be no issue with hooking.

Dobby is giving me an error I can't draw the imgui can you help me tg:@Beha_14jk

**Comment by reveny** [comment]
> > > yes I know that, but when you inject the x86 lib in armeabi-v7a you can't use the hook, for example, MSHOOK when you use the game it closes immediately or freezes and it's not just the MSHOOK that happens I tested several hooks and both give the same error
> > 
> > 
> > Imgui works fine with dobbyhook on x86 on emulator, I tried it on forward assault (game does not have x86, only armv7 and 64) and it renders just fine.
> > There should be no issue with hooking.
> 
> Dobby is giving me an error I can't draw the imgui can you help me tg:@Beha_14jk

You need to make sure that you build dobby for x86
